### ISSUE TITLE
🚀 Updated constants.ts: Corrected OpenRouter Model Names, Added New Model Names & Set Claude 3.5 Sonnet Beta as Default! 🌟

### ISSUE THREAD

**Issue by champ2050** [stackblitz-labs/bolt.diy#144]
I’ve created a Gist with my proposed updates to the constants.ts file. 

- This includes corrections to the OpenRouter model names.
- The addition of new OpenRouter models. 
- Lastly sets the latest Claude 3.5 Sonnet Beta from Openrouter as the default model. 
- You can check it out here: https://gist.github.com/champ2050/9ab77534e5eecbc1b999d8d8dddc99da

**P.S. I don’t know how to commit, so kindly consider adding this during the next model update to ensure we have the latest versions.

**Comment by hillct** [comment]
It seems more practical to fetch OpenRouter [models](https://openrouter.ai/docs/models) from their API: https://openrouter.ai/api/v1/models much as has been done in the case of Ollama support.

**Comment by hillct** [comment]
I'm not crazy about the open router documentation, but it appears the complete /v1/models API call seems to require no authentication, no parameters and no active account paid or unpaid. Certainly that might change but for now the API call can be made without issue.
