### ISSUE TITLE
Github commit on every delta

### ISSUE THREAD

**Issue by mayurjobanputra** [stackblitz-labs/bolt.diy#246]
Would be great if we could specify (for every chat), a github URL, branch, access token, and username. Then each time a change is made to code, its committed to the repo automatically

**Describe alternatives you've considered:**

Allow us to specify the github details in a local config file

**Additional context:**

Been using GPTEngineer for a few weeks. It does this very well and completely seemlessly.

**Comment by ali00209** [comment]
#111
