### ISSUE TITLE
Option to import github repository similar to the cloud environment

### ISSUE THREAD

**Issue by smartbrapp** [stackblitz-labs/bolt.diy#323]
Option to import github repository similar to the cloud environment:
https://bolt.new/~/github.com/vinodsharma10x/saas-founder-hub

http://localhost:5173/~/github.com/vinodsharma10x/saas-founder-hub

When I try I get a 404 not found error.

I really need a way to import my projects, as it became unfeasible to continue with the bolt.new plan.

**Comment by chrismahoney** [comment]
This is definitely on the radar and prioritized, with a few pull request submissions related to it. Thank you for your patience while it's worked out.

**Comment by Blitchy** [comment]
we need thiss 🥲

**Comment by kochrt** [comment]
Where do you need help? Are you trying to keep the same model of appending the github url to the url path?

**Comment by smartbrapp** [comment]
yes, I keep the same pattern but I get error 404
