### ISSUE TITLE
Bolt general use issues on deployment

### ISSUE THREAD

**Issue by nextdoormarketing** [stackblitz-labs/bolt.diy#340]
### Describe the bug

Hello Community!

Just got Bolt deployed in a docker config with a valid Traefik Let's Encrypt cert in production.
General use seems ok but...

1. I am getting step-by-step guides without implementation. 
2. Errors on creating an app or if an app is created, it will not continue with errors on both sometimes. Note the example log below.
3. Tried using Groq with llama 3.1 70b but found had a rate limit on the first prompt but did not know unless I looked at the docker logs.
4. When an app is created it will not launch the dev environment or will not refresh if reprompted. 
5. Get No preview available on some apps for the preview.

![image](https://github.com/user-attachments/assets/7547f68e-236c-41e2-b0ed-1c71db523a45)

Log of that error: cat /home/.npm/_logs/2024-11-19T20_00_39_868Z-debug-0.log
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@10.2.3
2 info using node@v18.20.3
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/project/.npmrc Completed in 4ms
10 timing config:load:project Completed in 26ms
11 timing config:load:file:/home/.npmrc Completed in 14ms
12 timing config:load:user Completed in 14ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 4ms
14 timing config:load:global Completed in 4ms
15 timing config:load:flatten Completed in 1ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 49ms
18 timing npm:load:configload Completed in 49ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm run dev
22 verbose argv "run" "dev"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/home/.npm/_logs/2024-11-19T20_00_39_868Z-
26 verbose logfile /home/.npm/_logs/2024-11-19T20_00_39_868Z-debug-0.log
27 timing npm:load:logFile Completed in 5ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 59ms
31 timing command:run Completed in 4ms
32 verbose stack ENOENT: no such file or directory, open '/home/project/package.json'
33 verbose cwd /home/project
34 verbose Linux 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
35 verbose node v18.20.3
36 verbose npm  v10.2.3
37 error code ENOENT
38 error syscall open
39 error path /home/project/package.json
40 error errno -2
41 error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/project/package.json'
42 error enoent This is related to npm not being able to find a file.
42 error enoent
43 verbose exit -2
44 timing npm Completed in 81ms
45 verbose code -2
46 error A complete log of this run can be found in: /home/.npm/_logs/2024-11-19T20_00_39_868Z-debug-0.log

### Link to the Bolt URL that caused the error

https://bolt.local.mydomain.ca/

### Steps to reproduce

1. On the main page choose any of the examples for apps to create with any Groq model or Mistrial (Only APIs configured)
2. When the next screen is presented will have issues with tryting to reprompt, refreshing page, will not create files sometimes, etc... 

### Expected behavior

Act like the online Bolt.new page and work on app creation or prompts. 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/7547f68e-236c-41e2-b0ed-1c71db523a45)

### Platform

- Client OS: [Tried Windows 10 and Ubuntu Linux Ubuntu 24.04.1 LTS]
- Browser: [Google Chrome and Firefox]
- Version: [I think its aac9a98, 8 hours ago]
- Server OS: Ubuntu server Ubuntu 22.04.5 LTS. Docker version 27.3.1, build ce12230

### Additional context

I am quite sure it's a config but not sure, seems related to the web container technology but still unsure.

**Comment by chrismahoney** [comment]
Failure to initialize vite properly is responsible for the majority of these issues in my experience via smaller models. There should be some prioritized updates that come through to address these and other scenarios, it is very important to myself as a consumer/user.

**Comment by nextdoormarketing** [comment]
Thank you! Are you able to update me and I can redeploy and test? Thank you @chrismahoney !

**Comment by dustinwloring1988** [comment]
please try the latest version
