### ISSUE TITLE
Error: write EOF when running pnpm run dev

### ISSUE THREAD

**Issue by beenycool** [stackblitz-labs/bolt.diy#354]
### Describe the bug

When running pnpm run dev in the bolt.new-any-llm project, the terminal throws a write EOF error, and the process exits with code 1. The issue persists even after reinstalling dependencies, clearing the cache, and ensuring Node.js and PNPM versions are up-to-date. There are also warnings related to Remix Router v7 during the process.

### Link to the Bolt URL that caused the error

idk

### Steps to reproduce

pnpm run dev

### Expected behavior

C:\Users\******\bolt.new-any-llm>pnpm run dev

> bolt@ dev C:\Users\******\bolt.new-any-llm
> remix vite:dev

warn  Route discovery/manifest behavior is changing in React Router v7
┃ You can use the `v3_lazyRouteDiscovery` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_lazyRouteDiscovery
┗
warn  Data fetching is changing to a single fetch in React Router v7
┃ You can use the `v3_singleFetch` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
┗
Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:87:19)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -4095,
  code: 'EOF',
  syscall: 'write'
}
 ELIFECYCLE  Command failed with exit code 1.

### Screen Recording / Screenshot

This issue started occurring after a fresh clone of the repository. I've tried clearing PNPM cache, reinstalling dependencies

### Platform

Windows 11 24H2
PNPM: 9.14.2
Node.js:23.2.0

### Additional context

Thanks for your hard work btw

**Comment by navitaaa1** [comment]
I am facing the issues

**Comment by dustinwloring1988** [comment]
most of these should be fixed you should only see one warning correct?

**Comment by navitaaa1** [comment]
Yes, thank you very much.

**Comment by newmemberninja** [comment]
how to fix that? or any workarounds?

**Comment by dustinwloring1988** [comment]
@newmemberninja I don't see a question can you try again

**Comment by newmemberninja** [comment]
-- Please reply above this line --


Hey Stackblitz-Labs/bolt.diy,

We received your email request! Someone from our team will get back to
you as soon as possible.

Your ticket number is: 23839

Thank you!

**Comment by beenycool** [comment]
il try again, but it works with docker but its not ideal

**Comment by newmemberninja** [comment]
-- Please reply above this line --


Hey Stackblitz-Labs/bolt.diy,

We received your email request! Someone from our team will get back to
you as soon as possible.

Your ticket number is: 23866

Thank you!

**Comment by newmemberninja** [comment]
@dustinwloring1988 apologies my ticketing system was auto replying.

**Comment by beenycool** [comment]
tysm!
