### ISSUE TITLE
idk why i get this when i am trying to run it

### ISSUE THREAD

**Issue by Anormalman1** [stackblitz-labs/bolt.diy#366]
![image](https://github.com/user-attachments/assets/cf0fac17-84e0-4101-8b3c-dc51b084d420)

**Comment by radumalica** [comment]
It seems `wrangler` is having trouble running on Windows (you error comes from miniflare/cloudflare package which is used only by wrangler worker to serve locally the content). Try bumping the version down a bit from package.json . By default is 3.63.2, try using 3.57.1 and see if that works

**Comment by aliasfoxkde** [comment]
Check you have the latest version of Visual Studio C++ installed (14.40.33816)

See: https://github.com/coleam00/bolt.new-any-llm/issues/19

If that doesn't work, I'd try updating npm `npm install -g npm@latest`, cleanup (clear the node_modules), and run through the instructions again.

**Comment by dustinwloring1988** [comment]
did the fix above help?

**Comment by aliasfoxkde** [comment]
Diddo, anyone confirm this?

**Comment by aliasfoxkde** [comment]
This has been confirmed by a user on the think-tank forum, it can be closed but should be added to a knowledge base if one gets made. 

"After updating my Visual Studio c++ to 14.42…(the latest version now) i can finaly startup my BOLT.DIY.Thank you for all your help."

https://thinktank.ottomator.ai/t/bolt-diy-will-not-startup-with-the-commands/2179/15
