### ISSUE TITLE
Having wrong file contents in the exported files

### ISSUE THREAD

**Issue by rinne** [stackblitz-labs/bolt.diy#373]
### Describe the bug

I created a small web project with git main head yesterday 20241121 with GPT-4o.

The file contents look fine in the browser window with JS in main.js HTML in index.html and JSON in package.json.

However if I download the source code or sync it to local folder, the package.json contains an older version if index.html instead of actual package manifest JSON.

### Link to the Bolt URL that caused the error

http://127.0.0.1:5173/chat/swiperjs-website

### Steps to reproduce

I just used simple textual prompts to create the project.  I didn't edit the code myself at all.

### Expected behavior

The synced file tree to match whatever shows in the code editor in the web page.

### Platform

- Browser in MacOS, Bolt running with docker-compose in Linux
- Browser: Chrome
- Version: Latest

### Additional context

<img width="752" alt="image" src="https://github.com/user-attachments/assets/8d43c756-70d3-4733-97ae-cb43e5a3c939">
<img width="679" alt="image" src="https://github.com/user-attachments/assets/2e77b5cc-778a-4695-bfa3-c1b258a9ae5d">

**Comment by dustinwloring1988** [comment]
please try the latest version
