### ISSUE TITLE
I am always facing same issue 

### ISSUE THREAD

**Issue by Jeyari** [stackblitz-labs/bolt.diy#375]
### Describe the bug

![Capture](https://github.com/user-attachments/assets/aa77ffde-ac72-4a21-9095-582b99b5e757)

whenever trying to run npm install or run dev I got this issue 

❯ npm install && npx prisma init --datasource-provider sqlite
npm ERR! Unterminated string in JSON at position 1521791 (line 1 column 1521792)

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-22T13_51_14_028Z-debug-0.log

~/project 7m 12s
❯ 

~/project
❯ npm run dev

> e-commerce@1.0.0 dev
> next dev

jsh: command not found: next

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

This is issue that I am facing from the beginning of trying this tool

❯ npm install && npx prisma init --datasource-provider sqlite
npm ERR! Unterminated string in JSON at position 1521791 (line 1 column 1521792)

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-22T13_51_14_028Z-debug-0.log

~/project 7m 12s
❯ 

~/project
❯ npm run dev

> e-commerce@1.0.0 dev
> next dev

jsh: command not found: next

### Expected behavior

When I run npm install it says there is an error .
and says 

❯ npm install 
npm ERR! Unterminated string in JSON at position 1521791 (line 1 column 1521792)

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-22T13_51_14_028Z-debug-0.log

~/project 7m 12s
❯ 

~/project
❯ npm run dev

> e-commerce@1.0.0 dev
> next dev

jsh: command not found: next

### Screen Recording / Screenshot

![Capture](https://github.com/user-attachments/assets/b8bb69cd-3827-4f2c-b3ce-54b88239061d)

### Platform

- OS:  Windows
- Browser: Chrome,
 [Version 131.0.6778.86 (Official Build) (64-bit)]

**Comment by remisco** [comment]
same problem

**Comment by RJClarke** [comment]
same problem.
And it just burns tokens trying to fix itself, when it just hits the same problem again.

**Comment by dustinwloring1988** [comment]
when you see that in bolts termin end current server and enter 'npm i .'

dose this work
