### ISSUE TITLE
Vite:css-post Error

### ISSUE THREAD

**Issue by daniiii5** [stackblitz-labs/bolt.diy#391]
### Describe the bug

[vite:css-post] css content for "" was not found
    at Object.renderChunk (file:///home/dani/bolt.new-any-llm/node_modules/.pnpm/vite@5.4.11_@types+node@22.9.3_sass-embedded@1.81.0_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:36388:19)
    at file:///home/dani/bolt.new-any-llm/node_modules/.pnpm/rollup@4.27.4/node_modules/rollup/dist/es/shared/node-entry.js:20812:40 {
  code: 'PLUGIN_ERROR',
  plugin: 'vite:css-post',
  hook: 'renderChunk'
}
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

### Link to the Bolt URL that caused the error

I do not have this

### Steps to reproduce

execute pnpm preview

### Expected behavior

To work

### Platform

- OS: Windows 11
- Browser: None used in this bug
- Version: [e.g. 91.1]

**Comment by rohankm** [comment]
facing same error
