### ISSUE TITLE
### Minor Bug: Blank tooltip for Export icon and request to add hover text colour changes for other icons

### ISSUE THREAD

**Issue by champ2050** [stackblitz-labs/bolt.diy#409]
### Describe the bug

When hovering over the **Export** icon in the left-hand navigation bar, a blank white box (tooltip) is displayed. Additionally, the text colour of the icon remains white on hover, making it difficult to confirm visually that the mouse is on the icon. Despite this, clicking the Export icon works as expected and triggers the download properly.

#### **Additional Feature Request:**  
For consistency and better user experience, it would be helpful to apply the same hover text colour change (e.g., to **red**) to the other navigation icons in the left-hand menu. This behaviour would provide users with clear visual feedback when hovering over any icon.

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

1. Navigate to the left-hand navigation bar in the application.  
2. Hover the mouse pointer over the **Export** icon.  
3. Repeat the same for other icons in the navigation bar (e.g., Delete) to observe hover behaviour.  

### Expected behaviour

- The **Export** icon should display a clear and meaningful tooltip when hovered over.  
- The text colour of the **Export** and other navigation icons should change (e.g., to **red**) on hover, providing consistent visual feedback.  

#### **Proposed Fix:**  

1. Ensure the tooltip for the **Export** icon displays correctly with meaningful content.  
2. Update the hover state for the **Export** icon and other navigation icons to change the text colour (e.g., to **red**) for improved clarity and usability.  

### Platform

- OS: Windows 10
- Browser: Canary

### Additional context

While the Export icon’s functionality works as expected, addressing the tooltip and hover feedback issues would significantly enhance usability. Extending the hover colour change to all navigation icons would ensure consistency and improve the overall user experience.

**Comment by SujalXplores** [comment]
Raised PR #422 to address this issue
