### ISSUE TITLE
###Feature Request: 🚀 Add Dynamic Integration, Remove Duplicate Models for Hugging Face Models & Include Qwen/QwQ-32B-Preview

### ISSUE THREAD

**Issue by champ2050** [stackblitz-labs/bolt.diy#514]
**Description:**  
Currently, the Hugging Face models are **_duplicated_** in the dropdown menu. Additionally, the new `Qwen/QwQ-32B-Preview` model is missing from the list. It seems the model list is manually hardcoded. To improve usability and reduce manual updates, it would be beneficial to implement a dynamic way of fetching the latest models directly from Hugging Face.  

**Benefits:**  
- Automatically includes new models as they are released.  
- Eliminates the need for manual updates whenever a new model becomes available.  
- Reduces the likelihood of duplicate entries in the dropdown list.  

**Proposed Solution:**  
- Fetch the list of models dynamically via Hugging Face's API or other reliable means.  
- Ensure proper de-duplication logic is implemented in the dropdown rendering process.  

This enhancement would ensure the tool stays up-to-date with minimal manual intervention and provide a seamless experience for users.

**Comment by thecodacus** [comment]
check these PRs
https://github.com/stackblitz-labs/bolt.diy/pull/943
https://github.com/stackblitz-labs/bolt.diy/pull/513

currently loading dynamic for hugging fae will be a challenge, as they have huge list of models
