### ISSUE TITLE
The request use more GPU memory that normal

### ISSUE THREAD

**Issue by Yota73** [stackblitz-labs/bolt.diy#556]
### Describe the bug

Hi, I'm using this amazing project with success but with a strange behavior.
The model loaded in the GPU use more RAM that normally do.
For example, if I run qwen2.5-coder:14b that weights 9GB in the GPU ram, wen I start with "ollama run" I see in nvidia-smi 10696MiB/16376MiB and all work fine.
Using bolt I see 14756MiB/16376MiB and the system use the CPU.
With a smaller model bolt works normally.
I'm using ollama hosted on a different server (in the same LAN) that expose the API.

I'm pretty sure I'm missing some points .... can anyone help me?
Thanks

### Link to the Bolt URL that caused the error

no error, only super slow cause CPU work

### Steps to reproduce

Just start

### Expected behavior

Use the same amount of GPU memory of normal ollama usage.

### Platform

OS Linux Ubuntu 24.04
Browser Chrome

### Model Used

qwen2.5-coder:14b

**Comment by Yota73** [comment]
Thanks kekePower, I'm trying to figure out where the second call is. I tried both docker and pnpm versions with no success.
Could it be that Ollama is on another server in the local network?

**Comment by thecodacus** [comment]
llm's context consumes exponentially more memory as we increase the context length. 

and when running bolt, the system prompt itself is near 4k tokens. so here are the few tests before moving forward with any other investigation, try running in ollama with 4k context in the prompt and see the ram usage?
