### ISSUE TITLE
Failed to load url isomorphic-git

### ISSUE THREAD

**Issue by HamidNori** [stackblitz-labs/bolt.diy#586]
### Describe the bug

12:09:29 AM [vite] Pre-transform error: Failed to load url isomorphic-git (resolved id: isomorphic-git) in /app/app/lib/hooks/useGit.ts. Does the file exist?
app-dev-1  | 12:09:29 AM [vite] Pre-transform error: Failed to load url isomorphic-git/http/web (resolved id: isomorphic-git/http/web) in /app/app/lib/hooks/useGit.ts. Does the file exist?
app-dev-1  | 12:09:32 AM [vite] Error when evaluating SSR module /app/lib/hooks/useGit.ts: failed to import "isomorphic-git"
app-dev-1  | |- Error: Cannot find module 'isomorphic-git' imported from '/app/app/lib/hooks/useGit.ts'
app-dev-1  |     at nodeImport (file:///app/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:53047:19)
app-dev-1  |     at ssrImport (file:///app/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52914:22)
app-dev-1  |     at eval (/app/app/lib/hooks/useGit.ts:8:37)
app-dev-1  |     at instantiateModule (file:///app/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5)

### Link to the Bolt URL that caused the error

https://github.com/coleam00/bolt.new-any-llm

### Steps to reproduce

Steps to Reproduce in a Docker Environment**

1. Prepare the Docker Environment:
   - Ensure you have Docker installed and running.
   - Verify the Docker version:
     ```bash
     docker --version
     ```
   - Example output:
     ```
     Docker version 24.0.6, build ed223bc
     ```

2. **Clone the Repository or Access the Project**:
   - Clone the repository or navigate to your project directory:
     ```bash
     git clone <repository-url>
     cd <project-directory>
     ```

3. **Verify the `Dockerfile`**:
   - Open the `Dockerfile` and ensure it includes steps to install dependencies. For example:
     ```dockerfile
     FROM node:18-alpine
     WORKDIR /app
     COPY package.json ./
     COPY package-lock.json ./
     RUN npm install
     COPY . .
     CMD ["npm", "run", "dev"]
     ```
   - Make sure the `isomorphic-git` dependency is listed in `package.json`.

4. **Build the Docker Image**:
   - Run the build command:
     ```bash
     docker build -t my-app .
     ```

5. **Run the Docker Container**:
   - Start the container:
     ```bash
     docker run -p 3000:3000 my-app
     ```

6. **Trigger the Issue**:
   - Open your browser and navigate to `http://localhost:3000`.
   - Perform actions that invoke the code in `useGit.ts`.

7. **Observe the Error**:
   - Note any errors in the container logs:
     ```bash
     docker logs <container-id>
     ```
   - Example output:
     ```
     Cannot find module 'isomorphic-git' imported from '/app/app/lib/hooks/useGit.ts'
     ```

### Expected behavior

run bolt,new in my browser

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by aliasfoxkde** [comment]
pnpm install isomorphic-git 
pnpm install

That's will add it to your package.json which should be then updated in the main repo.

**Comment by thecodacus** [comment]
this is a duplicate #630
