### ISSUE TITLE
Max Token Allowed 8192? Why?

### ISSUE THREAD

**Issue by ernexto** [stackblitz-labs/bolt.diy#623]
Hello guys, just for information, I see you added exp-1206 and that's great, but why did you put the token limit at 8192? This model can handle MUCH more. What am I missing?

{ name: 'gemini-exp-1206', label: 'Gemini exp-1206', provider: 'Google', maxTokenAllowed: 8192 }

**Comment by ravindranantony** [comment]
in the .env file you can update DEFAULT_NUM_CTX= as much as you want

**Comment by averageaidude** [comment]
@ravindranantony that is not correct! 
@ernexto You are right this bug exist. I guess you run Bolt.diy local?

I tested it local with Oobabooga and run into the same issue. 

```
INFO   stream-text  Model "GLM-4.5-Air-MXFP4_MOE_S-00001-of-00005.gguf" is reasoning model: false, using maxTokens: 8192
 WARN   stream-text  Token limit warning: requesting 8192 tokens but model supports max 8000
 INFO   stream-text  DEBUG STREAM: Options filtering for model "GLM-4.5-Air-MXFP4_MOE_S-00001-of-00005.gguf": {
  "isReasoning": false,
  "originalOptions": {
    "supabaseConnection": {
      "isConnected": false,
      "hasSelectedProject": false,
      "credentials": {}
    },
    "toolChoice": "auto",
    "tools": {},
    "maxSteps": 5
  },
  "filteredOptions": {
    "supabaseConnection": {
      "isConnected": false,
      "hasSelectedProject": false,
      "credentials": {}
    },
    "toolChoice": "auto",
    "tools": {},
    "maxSteps": 5
  },
  "originalOptionsKeys": [
    "supabaseConnection",
    "toolChoice",
    "tools",
    "maxSteps",
    "onStepFinish",
    "onFinish"
  ],
  "filteredOptionsKeys": [
    "supabaseConnection",
    "toolChoice",
    "tools",
    "maxSteps",
    "onStepFinish",
    "onFinish"
  ],
  "removedParams": []
}
 INFO   stream-text  DEBUG STREAM: Final streaming params for model "GLM-4.5-Air-MXFP4_MOE_S-00001-of-00005.gguf": {
  "hasTemperature": false,
  "hasMaxTokens": true,
  "hasMaxCompletionTokens": false,
  "paramKeys": [
    "maxTokens",
    "supabaseConnection",
    "toolChoice",
    "tools",
    "maxSteps",
    "onStepFinish",
    "onFinish"
  ],
  "streamParams": {
    "maxTokens": 8192,
    "supabaseConnection": {
      "isConnected": false,
      "hasSelectedProject": false,
      "credentials": {}
    },
    "toolChoice": "auto",
    "tools": {},
    "maxSteps": 5
  }
}
 DEBUG   api.chat  usage {"promptTokens":6162,"completionTokens":502,"totalTokens":6664}
```


```
# Example Context Values for qwen2.5-coder:32b
# 
# DEFAULT_NUM_CTX=32768 # Consumes 36GB of VRAM
# DEFAULT_NUM_CTX=24576 # Consumes 32GB of VRAM
# DEFAULT_NUM_CTX=12288 # Consumes 26GB of VRAM
# DEFAULT_NUM_CTX=6144 # Consumes 24GB of VRAM
DEFAULT_NUM_CTX=32768
```

Bolt.diy does limit at least when using using local OPENAI_LIKE_API_BASE_URL even if .env.local is set to DEFAULT_NUM_CTX=32768.

Also streaming llm connection keeps open to long which leads to Browser freeze. If i run the same coding task direct in Oobabooga it spits out the space invaders code in seconds and one go. 

And also it does not help if you start vanilla-vite-template.git is buggy and produces the first error before a AI model is even doing its work:

```
~/project
❯ npm run dev

> vite-starter@0.0.0 dev
> vite

jsh: command not found: vite

~/project
❯ 
```
Just mentioning ;-)

**Comment by abilliontokens** [comment]
Having the same issue with glm coding plan 4.6
DEFAULT_NUM_CTX= is set to 200000

INFO   stream-text  Model "glm-4.6" is reasoning model: false, using maxTokens: 8192
 WARN   stream-text  Token limit warning: requesting 8192 tokens but model supports max 8000
 INFO   stream-text  DEBUG STREAM: Options filtering for model "glm-4.6": {
  "isReasoning": false,
  "originalOptions": {
    "supabaseConnection": {
      "isConnected": false,
      "hasSelectedProject": false,
      "credentials": {}
    },
    "toolChoice": "auto",
    "tools": {},
    "maxSteps": 5
  },
  "filteredOptions": {
    "supabaseConnection": {
      "isConnected": false,
      "hasSelectedProject": false,
      "credentials": {}
    },
    "toolChoice": "auto",
    "tools": {},
    "maxSteps": 5
  },
  "originalOptionsKeys": [
    "supabaseConnection",
    "toolChoice",
    "tools",
    "maxSteps",
    "onStepFinish",
    "onFinish"
  ],
  "filteredOptionsKeys": [
    "supabaseConnection",
    "toolChoice",
    "tools",
    "maxSteps",
    "onStepFinish",
    "onFinish"
  ],
  "removedParams": []
}
 INFO   stream-text  DEBUG STREAM: Final streaming params for model "glm-4.6": {
  "hasTemperature": false,
  "hasMaxTokens": true,
  "hasMaxCompletionTokens": false,
  "paramKeys": [
    "maxTokens",
    "supabaseConnection",
    "toolChoice",
    "tools",
    "maxSteps",
    "onStepFinish",
    "onFinish"
  ],
  "streamParams": {
    "maxTokens": 8192,
    "supabaseConnection": {
      "isConnected": false,
      "hasSelectedProject": false,
      "credentials": {}
    },
    "toolChoice": "auto",
    "tools": {},
    "maxSteps": 5
  }
}
