### ISSUE TITLE
Cannot find module 'isomorphic-git' imported from '/app/app/lib/hooks/useGit.ts' Error from last pull

### ISSUE THREAD

**Issue by arieltoledo** [stackblitz-labs/bolt.diy#630]
### Describe the bug

Using docker-compose to leverage container returns the error: Cannot find module 'isomorphic-git' imported from '/app/app/lib/hooks/useGit.ts'

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

1.- Git pull.
2.- docker-compose --profile development up -d

### Expected behavior

Get the app running

### Screen Recording / Screenshot

![screencapture-localhost-5173-2024-12-10-17_39_59](https://github.com/user-attachments/assets/c1be851a-7ecf-409a-b9f1-e0153d8e1d00)

### Platform

Windows 10
Browser: Chrome Versión 131.0.6778.109 (Build oficial) (64 bits)

**Comment by thecodacus** [comment]
before starting the server do a pnpm install first 
in the new updates there are few new packages were introduced

**Comment by arieltoledo** [comment]
@thecodacus 
I did it inside the container. And then added to the Dockerfile. Still same error

**Comment by thecodacus** [comment]
thats weird, can you pull the latest code from the repo

**Comment by arieltoledo** [comment]
Just clone the repo. And do a  docker-compose up --profile developer up -d

**Comment by youcef-belallou** [comment]
<img width="1248" alt="Screen Shot 2024-12-11 at 18 53 45" src="https://github.com/user-attachments/assets/a6a47033-2a24-45dd-9604-f4a2ddb27c22" />

**Comment by youcef-belallou** [comment]
@arieltoledo are you still having the same issue or you solved it .....bcs me I am having the same issue as you mentioned above

**Comment by thecodacus** [comment]
can you see that is the commit hash value in the clonned repo
its in the commit.json file in the root directory

**Comment by youcef-belallou** [comment]
@thecodacus { "commit": "0b9fd89c7089e98cfc2c17b6fd6ed7cdd6517f1a" }

**Comment by thecodacus** [comment]
so you are using an older version 
![Screenshot 2024-12-12 at 11 46 04 PM](https://github.com/user-attachments/assets/e03bd972-21c1-4f63-a3f9-2f6d7359b588)

**Comment by arieltoledo** [comment]
I jus do a git clone https://github.com/stackblitz-labs/bolt.diy.git. And the docker-compose up -d. Maybe had git cache something ?

**Comment by youcef-belallou** [comment]
<img width="1249" alt="Screen Shot 2024-12-12 at 19 21 17" src="https://github.com/user-attachments/assets/0b10a6cf-2abe-4443-a234-b7a93457ab35" />
i pulled the last commits put still the same commit hash value

**Comment by thecodacus** [comment]
yes sorry i missed the hash value..
can you try this command ??
`docker-compose --profile development up --build`

**Comment by thecodacus** [comment]
this should rebuild the container... it maybe using an older version from cache

**Comment by arieltoledo** [comment]
@thecodacus docker-compose --profile development up --build This worked !!! thanks, it was an old image messing around. Thabks and sorry for the inconvinience.

**Comment by thecodacus** [comment]
no problem.. anything for goku 😉

**Comment by thecodacus** [comment]
also added this PR, for future cases, will know exactly what commit version is running 

#668
