### ISSUE TITLE
Basic Usage

### ISSUE THREAD

**Issue by dustinwloring1988** [stackblitz-labs/bolt.diy#642]
https://github.com/user-attachments/assets/b9ef4309-15d2-46b7-84c5-ee8a46ee475e

**Comment by youcef-belallou** [comment]
<img width="1248" alt="Screen Shot 2024-12-11 at 18 53 45" src="https://github.com/user-attachments/assets/c66fddfd-1625-4de9-b18c-d8870499f33f" />
