### ISSUE TITLE
连接超时，未返回任何信息

### ISSUE THREAD

**Issue by veancn** [stackblitz-labs/bolt.diy#659]
### Describe the bug

连接超时，未返回任何信息。

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/4

### Steps to reproduce

![boltanyllm Error](https://github.com/user-attachments/assets/c515c92b-d534-478d-a9a3-e0dde8deaec1)

### Expected behavior

预期是程序停止了。

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ravindranantony** [comment]
use OLLAMA_API_BASE_URL=http://127.0.0.1:11434 and try the app in your .env

**Comment by ravindranantony** [comment]
try to reinstall your node modules

**Comment by pjmartorell** [comment]
this error comes from your Ollama installation and it's not related with Bolt.diy

**Comment by veancn** [comment]
谢谢。以经处理好，可以运行。

**Comment by veancn** [comment]
谢谢，已经正常运行。祝福美好！----- 原始邮件 ***@***.***>发送时间：2024-12-12 ***@***.***>***@***.***>***@***.***>主 题：Re: [stackblitz-labs/bolt.diy] 连接超时，未返回任何信息 (Issue #659)
try to reinstall your node modules
