### ISSUE TITLE
Initial startup issue - no providers are currently enabled 

### ISSUE THREAD

**Issue by ravindranantony** [stackblitz-labs/bolt.diy#664]
### Describe the bug

everything is setup right but gets into this.

![image](https://github.com/user-attachments/assets/21bf05d2-5037-45fe-9695-22d263a6b075)

### Link to the Bolt URL that caused the error

lcoalhost

### Steps to reproduce

Go to localhost
Try to Change the Model 

### Expected behavior

It should be possible to select and run the model. after model selection box the next text box also goes empty

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Provider Used

unable to start

### Model Used

many models 

### Additional context

never run earlier

**Comment by FrozenKnight-69** [comment]
im having the same problem,is your .env.example file set to .env.local or just .env?

**Comment by quicksaasdev** [comment]
Same here.

**Comment by quicksaasdev** [comment]
> im having the same problem,is your .env.example file set to .env.local or just .env?

Mine is env.local

**Comment by FrozenKnight-69** [comment]
> > im having the same problem,is your .env.example file set to .env.local or just .env?
> 
> Mine is env.local

then we three are having the same issue

**Comment by ravindranantony** [comment]
I just changed to .env but still does not work.

**Comment by FrozenKnight-69** [comment]
> I just changed to .env but still does not work.
I found the issue,
Go to settings(Hover you mouse towards the left side of the screen and you will find a panel and you can send your settings option below the panel) and then go to providers section in the settings and enable all the providers you need

**Comment by quicksaasdev** [comment]
Thanks. 

> > I just changed to .env but still does not work.
> > I found the issue,
> > Go to settings(Hover you mouse towards the left side of the screen and you will find a panel and you can send your settings option below the panel) and then go to providers section in the settings and enable all the providers you need

**Comment by FrozenKnight-69** [comment]
> Thanks.
> 
> > > I just changed to .env but still does not work.
> > > I found the issue,
> > > Go to settings(Hover you mouse towards the left side of the screen and you will find a panel and you can send your settings option below the panel) and then go to providers section in the settings and enable all the providers you need

working?

**Comment by ravindranantony** [comment]
yes this solution is working. once you see the localhost, go to the settings and select the providers you had given in the .env file. 

enable what ever the api key you had given only. 

![image](https://github.com/user-attachments/assets/621bd18a-de7f-4668-9df1-4e876538acb0)

I had supplied 4 API keys and I am enabling only that.

now works.

**Comment by MAWAAW** [comment]
I just installed the git project to see the error but I don't have it
![image](https://github.com/user-attachments/assets/704dc576-6220-460f-8dbf-142251ba6150)

**Comment by FrozenKnight-69** [comment]
> I just installed the git project to see the error but I don't have it ![image](https://private-user-images.githubusercontent.com/16020356/395162789-704dc576-6220-460f-8dbf-142251ba6150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDc0MzgsIm5iZiI6MTczNDAwNzEzOCwicGF0aCI6Ii8xNjAyMDM1Ni8zOTUxNjI3ODktNzA0ZGM1NzYtNjIyMC00NjBmLThkYmYtMTQyMjUxYmE2MTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDEyMzg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwOWE3YTU2MGRiYWEyY2M4MGExMTA2NDY0OTNkMGU2MDJjZTg0ZDM1N2YxNjZiN2FkMGJhMGU1N2NlNTNlOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0D0kT8xFznxANfBos1XKjPX4OWFJnxfDNSaJtGvjvPU)

Maybe you have the providers setting enabled

**Comment by ravindranantony** [comment]
is the application works now ?

**Comment by FrozenKnight-69** [comment]
> is the application works now ?

yes

**Comment by quicksaasdev** [comment]
I have uploaded the project after downloading it from bolt.
 I am using anthropic and getting an error - 
<img width="318" alt="Screenshot 2024-12-12 at 4 49 53 PM" src="https://github.com/user-attachments/assets/72620e9c-2507-4bb7-afb6-291cf0080207" />

**Comment by MAWAAW** [comment]
> I have uploaded the project after downloading it from bolt. I am using anthropic and getting an error - <img alt="Screenshot 2024-12-12 at 4 49 53 PM" width="318" src="https://private-user-images.githubusercontent.com/183183921/395166629-72620e9c-2507-4bb7-afb6-291cf0080207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDg0MDcsIm5iZiI6MTczNDAwODEwNywicGF0aCI6Ii8xODMxODM5MjEvMzk1MTY2NjI5LTcyNjIwZTljLTI1MDctNGJiNy1hZmI2LTI5MWNmMDA4MDIwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQxMjU1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTgxZjliZDM1ZjUyNjYxNjAzMDgyZDU4MTVmZTNiZTZmYjk2NjczM2U0ZTUzYTFiYmEyZTczMjc4OTk5NDY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2exTT2xcQ5vaCi5hYdrFL9IdipmWK5O9JjmeZVnDa10">

You probably have this trace ?
APICallError [AI_APICallError]: Not Found
at ..........
  cause: undefined,
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 32768, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '78',
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 12 Dec 2024 12:55:55 GMT'
  },
  responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}

**Comment by Bazz0r** [comment]
> I use ollama, but why Claude Showing up? Still cannot use it. ![image](https://private-user-images.githubusercontent.com/3888252/395192221-611c02f6-cf07-4ff7-bf68-d12e7677cb43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMjYwMDUsIm5iZiI6MTczNDAyNTcwNSwicGF0aCI6Ii8zODg4MjUyLzM5NTE5MjIyMS02MTFjMDJmNi1jZjA3LTRmZjctYmY2OC1kMTJlNzY3N2NiNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMTc0ODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjIwZDYzOTM3ZDkzOTRjNzY3ZTlhYjI3MWY4Yzg2YmVmNWFhMDRlMjBhM2U3OWQ0YWNmYmRjYWQ0N2Y3NDA4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qUOcyMOPOvoWsMFLgk60myKb1C7Uw_Cj6QxaJc6ovZQ)

I have the same issue, doesn't matter what provider you select, it only shows Anthropic models.

**Comment by rexsama** [comment]
![image](https://github.com/user-attachments/assets/cc9f2a01-c2a3-4497-85b1-51338b651d9b)
I had the same issue, plus getting another error "Failed to read large IndexedDB value"

**Comment by thecodacus** [comment]
> I use ollama, but why Claude Showing up? Still cannot use it. ![image](https://private-user-images.githubusercontent.com/3888252/395192221-611c02f6-cf07-4ff7-bf68-d12e7677cb43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNjkzNDMsIm5iZiI6MTczNDA2OTA0MywicGF0aCI6Ii8zODg4MjUyLzM5NTE5MjIyMS02MTFjMDJmNi1jZjA3LTRmZjctYmY2OC1kMTJlNzY3N2NiNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTNUMDU1MDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU1NWY0YTExMDA2YmQ5ZTcxODJhYTA0NmUzZmUzNzgzMjZjN2E5ZjIwMjQ3MTViYTk1MzJiOGQ1NTVjYmY3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TF1WLd9UUhKO1tTrjHsk-Me8SMgpS8drKnjnfE7SnYw)

this is a bug thats happens when you disables one of the active provider which was selected before you disabled it.

should be working if you just change to provider to something else and then back to Ollama

the initial issue regarding the default providers were not enabled is now fixed 

#683

**Comment by thecodacus** [comment]
#684 this should fix the issue mentioned in the thread
