### ISSUE TITLE
Error when access bolt.diy Cannot read properties of null (reading 'useEffect')

### ISSUE THREAD

**Issue by private1403** [stackblitz-labs/bolt.diy#667]
### Describe the bug

error on access bolt.diy

here error message on browser : 

Unexpected Server Error

TypeError: Cannot read properties of null (reading 'useEffect')

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

go to http://localhost:5173/

### Expected behavior

error on access bolt.diy

here error message on browser : 

Unexpected Server Error

TypeError: Cannot read properties of null (reading 'useEffect')

### Platform

- OS: [Windows]
- Browser: [Chrome]

**Comment by leex279** [comment]
What version of nodejs you are running and how did you run bolt?

Did you checkout the "stable" branch instead of main and tried it?

Also please a screenshot of you terminal, where the commands and error can be seen.

**Comment by Tellivision** [comment]
I also get this using newest nodesjs and bolt.diy 
![image](https://github.com/user-attachments/assets/93aea3f4-fb9d-41ff-bc6e-28a6b5a1b14a)

**Comment by Walkidos** [comment]
same here, anyone solved the problem?
