### ISSUE TITLE
Error in package.json

### ISSUE THREAD

**Issue by Freffles** [stackblitz-labs/bolt.diy#678]
### Describe the bug

When starting the dev server with pnpm run dev, the following error is displayed.

> bolt@ dev D:\Working\RL_Scripts\Bolt\bolt.new-any-llm
> node pre-start.cjs;  remix vite:dev

node:internal/modules/cjs/loader:1252
  throw err;
  ^

Error: Cannot find module 'D:\Working\RL_Scripts\Bolt\bolt.new-any-llm\pre-start.cjs;'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

This appears to be due to an error on line 11 of the package,json:  "dev": "node pre-start.cjs;  remix vite:dev",

Semicolon should be && 

### Link to the Bolt URL that caused the error

na

### Steps to reproduce

pnpm run dev

### Expected behavior

Dev server starts

### Screen Recording / Screenshot

n/a

### Platform

Windows 10

### Provider Used

n/a

### Model Used

n/a

### Additional context

n/a

**Comment by ShaneG** [comment]
Worked for me to fix, thank you!

**Comment by saikumarbt** [comment]
I am also facing the same error. Appreciate any help :) 

![image](https://github.com/user-attachments/assets/9563ddd5-d72d-4298-8bbf-69083bb86294)

**Comment by saikumarbt** [comment]
> &&

Updating package.json line# to :  "dev": "node pre-start.cjs **&&**  remix vite:dev", 
Fixed the issue. Thanks @Freffles  :)

**Comment by thecodacus** [comment]
this issue is fixed #682
