### ISSUE TITLE
Debug Tab => Browser Recognition wrong

### ISSUE THREAD

**Issue by leex279** [stackblitz-labs/bolt.diy#749]
### Describe the bug

The Browser showing in the Settings -> Debug Tab is showing the wrong Browser (Safari instead of Chrome in my case).
![image](https://github.com/user-attachments/assets/088dc002-dda2-43bd-9535-09dc691b60cc)

Verified it is correct e.g. for openrouter.ai website => request-header:
![image](https://github.com/user-attachments/assets/6b4ecd84-20b1-4557-99ce-f2ae2bf9dffd)

### Link to the Bolt URL that caused the error

N/A

### Steps to reproduce

1. Go to "Settings"
2. Go to "Debug Tab"

### Expected behavior

Showing the correct Browser (Chrome in this case)

### Platform

- OS: [Windows,]
- Browser: [Chrome]

**Comment by Stijnus** [comment]
Hi,

Should be fixed it have created a pull request for the fix.

<img width="900" alt="image" src="https://github.com/user-attachments/assets/121a361c-032b-442a-ac71-9cf768d0bd93" />


Br,

Stijn

**Comment by leex279** [comment]
Works
![image](https://github.com/user-attachments/assets/57dc11aa-0824-4650-8212-187a932f14ae)

**Comment by thecodacus** [comment]
> Works, thanks :) ![image](https://private-user-images.githubusercontent.com/6664492/395912171-57dc11aa-0824-4650-8212-187a932f14ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjMyMjUsIm5iZiI6MTczNDM2MjkyNSwicGF0aCI6Ii82NjY0NDkyLzM5NTkxMjE3MS01N2RjMTFhYS0wODI0LTQ2NTAtODIxMi0xODdhOTMyZjE0YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTZUMTUyODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjIyMDk4MzhhNzI5ODQwMzliYzc3YTNhNDRkMjQ1MjdiZDYxMmNiNWM0NzVjZmYxOTA4NjBjMmU1MTFjMjBlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9FEzDngYykptNC5ql-aLMHYLGFl9YIAwh9odwNXCUYE)

@Stijnus  for display can we have a fixed decimal value instead of long floating point number like above
