### ISSUE TITLE
After installation, the server does not work correctly and I see error images with codes.

### ISSUE THREAD

**Issue by sei160** [stackblitz-labs/bolt.diy#768]
### Describe the bug

After installation, the server does not work correctly and I see error images with codes.

### Link to the Bolt URL that caused the error

After installation, the server does not work correctly and I see error images with codes.

### Steps to reproduce

After installation, the server does not work correctly and I see error images with codes.

### Expected behavior

After installation, the server does not work correctly and I see error images with codes.

### Screen Recording / Screenshot

After installation, the server does not work correctly and I see error images with codes.
![Skärmavbild 2024-12-16 kl  13 14 16](https://github.com/user-attachments/assets/950bb78e-05f1-4547-92ec-0a6b38a5c4e7)

### Platform

- OS: macOS
- Browser: Safari, 
- Version: 15.2

**Comment by thecodacus** [comment]
#771 should fix the issue

**Comment by sei160** [comment]
Thanks works better with chrom but still a error



Den mån 16 dec. 2024 17:02Anirban Kar <
***@***.***> skrev:

**Comment by thecodacus** [comment]
if this is a separate error please raise another issue. closing this one

**Comment by sei160** [comment]
Thank you for your support and assistance with the matter at hand. As we have resolved the issue, we are now closing this case.

Från: Anirban Kar ***@***.***>
Datum: måndag, 16 december 2024 22:16
Till: stackblitz-labs/bolt.diy ***@***.***>
Kopia: sei160 ***@***.***>, Author ***@***.***>
Ämne: Re: [stackblitz-labs/bolt.diy] After installation, the server does not work correctly and I see error images with codes. (Issue #768)

if this is a separate error please raise another issue. closing this one —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message
DuckDuckGo removed one tracker. More<https://duckduckgo.com/-vPjg-LDv9ohdnAQkqmZ9v3OjdbAtYEWA5oWkoNhpWYmq9oMzz0EJJo1nN1vgYEOOuDh7JQWJ9CgMXaF7gQAJsxid5TA0rB1d7_fv9CXyLf6J1wkXezi8BUHoLr4KnYHougeyodxVDVun9O9b5u8l1Gn1gCIld9Rxvej0PW5MDp1Lc2CsrgmgaDwIr6fkHDM6aH1wPp0ra-rR9uhYy5mJAPwjPrA6YCAIaExsuDRJeKQ6LgP6LGCVqMklDzq2I4Bk4-BPDEYPciPJGuIQNsMWcraVBqqKpF82JqeAqP0f4FnTBX2nya6iZvvDpdZBDJ6H29JSnZw066qPYtlU1goFDm-aIzXbPFHfP9ztIVjtx3FEhtMnewN4n7ga3RaUNTeCmCcfFbXEUXQh5hgcDw_Wfj0719Bkvql-Y7yfS6MTjktvipxFcYQMWmDDg>
Report Spam <https://duckduckgo.com/-vPjg-LDv9ohdnAQkqmZ9v3OjdbAtYEWA5oWkoNhpWYmq9oMzz0EJJo1nN1vgYEOOuDh7JQWJ9CgMXaF7gQAJsxid5TA0rB1d7_fv9CXyLf6J1wkXezi8BUHoLr4KnYHougeyodxVDVun9O9b5u8l1Gn1gCIld9Rxvej0PW5MDp1Lc2CsrgmgaDwIr6fkHDM6aH1wPp0ra-rR9uhYy5mJAPwjPrA6YCAIaExsuDRJeKQ6LgP6LGCVqMklDzq2I4Bk4-BPDEYPciPJGuIQNsMWcraVBqqKpF82JqeAqP0f4FnTBX2nya6iZvvDpdZBDJ6H29JSnZw066qPYtlU1goFDm-aIzXbPFHfP9ztIVjtx3FEhtMnewN4n7ga3RaUNTeCmCcfFbXEUXQh5hgcDw_Wfj0719Bkvql-Y7yfS6MTjktvipxFcYQMWmDDg>

if this is a separate error please raise another issue. closing this one
