### ISSUE TITLE
npm start fails with "No matching export in 'ai' for import 'createDataStream'"

### ISSUE THREAD

**Issue by rajpdus** [stackblitz-labs/bolt.diy#787]
### Describe the bug

When running npm start, the build process fails with the following error:
✘ [ERROR] No matching export in "../node_modules/ai/dist/index.mjs" for import "createDataStream"

      ../build/server/index.js:12:60:
        12 │ ...streamText$1, convertToCoreMessages, createDataStream } from 'ai';
           ╵                                         ~~~~~~~~~~~~~~~~
This error indicates that the createDataStream export is not found in the ai package's index.mjs file, but is being imported in ../build/server/index.js.

### Link to the Bolt URL that caused the error

localhost

### Steps to reproduce

Run npm start from the project root.
Expected Behavior:
The application should build and start successfully.
Actual Behavior:
The build process fails with the error message above.
Additional Information:
The error occurs during the wrangler pages dev command, which is part of the npm run start:unix script.
The ai package is likely a dependency of the project.

### Expected behavior

The server should start

### Screen Recording / Screenshot

<img width="1058" alt="image" src="https://github.com/user-attachments/assets/629add11-4dbc-4216-9b6a-43952c10cc90" />

### Platform

- OS: macOS
- Version: v0.0.2

**Comment by leex279** [comment]
Just to be sure, you did install first? Also I would recommend the mentioned commands from the docs, as these are testet. so use pnpm instead of npm

![image](https://github.com/user-attachments/assets/fbf5e93b-0226-4f94-bb16-1970923a5204)

**Comment by rajpdus** [comment]
That's strange but it works with pnpm.

**Comment by rajpdus** [comment]
Looks like something we can put to rest for now
