### ISSUE TITLE
API KEY  error processing

### ISSUE THREAD

**Issue by contabilulistet2** [stackblitz-labs/bolt.diy#793]
### Describe the bug

Hello,
No matter the Provider selected, I m getting the same error.
Providers selected in settings, API KEY set in .env.local and /or UI.
WIN 11/Docker
Release v0.0.2
Chrome, Edge, Chrome Canary

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

1. GoTo http://localhost:5173/
2. Select Provider
3. Insert API KEY
4.  Create a TODO app
5. there was an error processing your request: an error occurred

### Expected behavior

Expected to start the LLM selected and create project files

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/ad46a11b-0857-4dc2-9351-50d145f78cf6)

### Platform

- OS: Windows, 11
- Browser: [Chrome, Edge, Chrome Canary
- Version:  Release v0.0.2

### Provider Used

Any from the list

**Comment by contabilulistet2** [comment]
Thank you Dustin for the quick response.
- I have the latest version
- ERR_CONNECTION_REFUSED
- getting the same error for Ollama as well

**Comment by dustinwloring1988** [comment]
try to add the api keys and base url in the settings menu and see if this helps

**Comment by biratrai** [comment]
Seeing the same error

**Comment by contabilulistet2** [comment]
> Seeing the same error. Do we need to do anything after putting the api keys in env.local life just save the file?
> 
> Google api worked only after putting the api keys from the WebWindow

yes, did the same and it is now the only one working

**Comment by megaman5** [comment]
For me, instead of running it with docker-compose --profile development up
I used
docker run -p 5173:5173 --env-file .env.local bolt-ai:development
which apparently caused it to properly load the env file

**Comment by akshaynstack** [comment]
I am also facing this issue after building the project, on development mode works but build doesn't work
