### ISSUE TITLE
Vite throws error: The requested module 'ai' does not provide an export named 'createDataStream' (v0.0.2 & v0.0.3)

### ISSUE THREAD

**Issue by LoTimmy** [stackblitz-labs/bolt.diy#813]
### Describe the bug

![image](https://github.com/user-attachments/assets/20bad839-2a51-4b32-a774-a6e8048251b0)

When using version `v0.0.2` or `v0.0.3` of the `bolt.diy` project (https://github.com/stackblitz-labs/bolt.diy), Vite shows the following error:

```
The requested module 'bolt.diy' does not provide an export named 'createDataStream'
```

This issue does **not** occur when using version `v0.0.1` of the `bolt.diy` project.

The project is run using the following command:

```bash
docker-compose --profile development up  # Development
```

### Link to the Bolt URL that caused the error

https://bolt-dev.lotimmy.com/

### Steps to reproduce

1. Clone and set up the `bolt.diy` project from the repository:
   - Repository: https://github.com/stackblitz-labs/bolt.diy
2. Start the project using the following command:
   ```bash
   docker-compose --profile development up  # Development
   ```
3. Ensure version `v0.0.2` or `v0.0.3` of the `bolt.diy` project is used.
4. Access the route/file in your project that imports `createDataStream`.
5. Observe the Vite error:
   ```
   The requested module 'bolt.diy' does not provide an export named 'createDataStream'
   ```

### Expected behavior

The project should work correctly, and `createDataStream` should be successfully imported, as it works in version `v0.0.1` of the `bolt.diy` project.

### Platform

**Platform**:

- **OS**: Ubuntu 24.04 LTS (noble)
- **Version**:
  - **Docker**: 27.3.1, build ce12230
  - **Docker Compose**: v2.30.3

**Comment by thecodacus** [comment]
anytime you upgrade the version do a pnpm install first

**Comment by thecodacus** [comment]
@dustinwloring1988 might be a good idea to add that to the docs and readme

**Comment by andywahyudi** [comment]
Hi @thecodacus ,
I got the same issue. Running `docker-compose --profile development up --build` doesn't help. The issue still persists. Any insight? Thanks.

**Comment by smxsm** [comment]
After `docker-compose up ... --build`, also try `docker exec -it boltdiy-app-dev-1 pnpm install` to run pnpm install inside the container

**Comment by andywahyudi** [comment]
Hi @thecodacus & @smxsm ,
I removed the existing/previous containers, and re-run the docker compose up, and worked well. Thank you.
