### ISSUE TITLE
ERROR: Application Error, Bolt not able to import entire Github repo in the workbench

### ISSUE THREAD

**Issue by fahadpatel-nc** [stackblitz-labs/bolt.diy#824]
### Describe the bug

When I try to import small github repositories with 2-3 files, it works perfectly fine. But when I import a big github repo like stablitz bolt.diy it shows Application Error on the FrontendTypeError: Cannot read properties of undefined (reading 'runner')

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/30

### Steps to reproduce

1. Clone the bolt.diy repo
2. Run the setup and start the app on localhost
3. Click on "Clone a Git Repo"
4. Add the github repo url: https://github.com/stackblitz-labs/bolt.diy
5. Click on Ok

### Expected behavior

It should successfully load the entire github repository with all files and structures, so that it can be reference using Anthropic Claude 3.5 sonnet

### Screen Recording / Screenshot

<img width="1281" alt="Screenshot 2024-12-18 at 8 27 07 PM" src="https://github.com/user-attachments/assets/aef2f2b1-7f8c-4b49-9da6-9c89ab16a365" />

### Platform

- OS: macOS
- Browser: Chrome
- Version: latest version

### Provider Used

Tried with Anthropic and OpenAi

### Model Used

Claude 3.5 Sonnet, Gpt-4o

**Comment by thecodacus** [comment]
you will not be able to import bolt on bolt at the moment, as it has the system prompts inside the repo causing problems with the actual parser which is also trying to parse the system prompt from the cloned repo..

this is a rare scenario might only happen with bolt repo
