### ISSUE TITLE
how to run ollama model as it runing at custom ip like http://10.1.1.18:8080/

### ISSUE THREAD

**Issue by yuvrajarora1805** [stackblitz-labs/bolt.diy#833]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by thecodacus** [comment]
Hello!

Thank you for reaching out and trying to get bolt.diy up and running. We're glad you're interested in using our project.

Before we dive into troubleshooting, I'd like to encourage you to take a look at our [README ](https://github.com/stackblitz-labs/bolt.diy/blob/main/README.md)and especially the "Getting Started" section. It's designed to help new users get started with minimal fuss.

If you've already reviewed the documentation and still need some assistance, we'd be happy to take another look at your issue. Please make sure to provide detailed information about your setup, environment, and any error messages you're seeing (if applicable).

Let's work together to find a solution! If you have any further questions or concerns after reviewing the README, feel free to update this issue with more details."
