### ISSUE TITLE
 B O L T . D I Y (dyld: malformed mach-o image: dyld chained fixups info underruns __LINKEDIT)

### ISSUE THREAD

**Issue by guiverdoodt92** [stackblitz-labs/bolt.diy#834]
### Describe the bug

I`m not able to install Docker, versions not matching my OS, so I`m trying to run without Docker.

![Captura de Tela 2024-12-19 às 11 10 24](https://github.com/user-attachments/assets/808d69b9-e421-4df1-b95a-3a3a6db7fc60)

 HOW TO FIX IT? 

I`m running it on my macbook air Big Sur 11.7.10 version.

### Link to the Bolt URL that caused the error

no link

### Steps to reproduce

1. pnpm install
2. pnpm run dev

### Expected behavior

Run the local Bolt.diy

### Platform

- OS: macOS
- Cursor IDE
- Version: [11.7.10 - Big Sur]

**Comment by thecodacus** [comment]
i can see you are using much older version 0.0.1 latest one is 0.0.3 you can try that..
but the main issue might be related to your system, not bolt itself. 
in such scenario docker is the best choice. is there any specific reason for not able to use docker ?

**Comment by guiverdoodt92** [comment]
My Mac is old, that's why I couldn't run docker. It's not supported on Big
Sur version anymore.

Em qui., 19 de dez. de 2024 12:38, Anirban Kar ***@***.***>
escreveu:

**Comment by guiverdoodt92** [comment]
> i can see you are using much older version 0.0.1 latest one is 0.0.3 you can try that..
> but the main issue might be related to your system, not bolt itself. 
> in such scenario docker is the best choice. is there any specific reason for not able to use docker ?

Yes, my Mac is too old. Big Sur is out of any update. Docker do not support Old versions of Macs like mine, that's why I'm not able to run it.

**Comment by thecodacus** [comment]
okay. which version of node you are using ? can you update it it its below 18

**Comment by guiverdoodt92** [comment]
I'm using node v23.3.0

**Comment by guiverdoodt92** [comment]
You mean downgrade?

**Comment by thecodacus** [comment]
no its fine. the error you are facing is might be due to damaged executables. can you just remove the node_modules and reinstall the dependencies ?

**Comment by guiverdoodt92** [comment]
> no its fine. the error you are facing is might be due to damaged executables. can you just remove the node_modules and reinstall the dependencies ?

I'll try this. Thank you.

**Comment by guiverdoodt92** [comment]
It worked man! tks @thecodacus

**Comment by engmsaleh** [comment]
I have done as @thecodacus  suggested but it didn't solve the issue for me
I'm using 

```
osx 11.7.10
➜  ~ pnpm --version
9.15.3
➜  ~ npm --version
10.8.2
➜  ~ node --version
v20.17.0
```

Any other suggestions?
