### ISSUE TITLE
ERROR BEFORE RUN DEV

### ISSUE THREAD

**Issue by befikirrr** [stackblitz-labs/bolt.diy#835]
### Describe the bug

    at Object.run (/Users/befwon/bolt.diy/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy/node_modules/@remix-run/dev/dist/cli/run.js:271:7) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'

### Link to the Bolt URL that caused the error

oo

### Steps to reproduce

trying to run dev after downloading and getting this plz help

### Expected behavior

supposed to open bolt.diy

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Model Used

newest

**Comment by thecodacus** [comment]
Hello!

Thank you for reaching out and trying to get bolt.diy up and running. We're glad you're interested in using our project.

Before we dive into troubleshooting, I'd like to encourage you to take a look at our [README ](https://github.com/stackblitz-labs/bolt.diy/blob/main/README.md)and especially the "Getting Started" section. It's designed to help new users get started with minimal fuss.

If you've already reviewed the documentation and still need some assistance, we'd be happy to take another look at your issue. Please make sure to provide detailed information about your setup, environment, and any error messages you're seeing (if applicable).

Let's work together to find a solution! If you have any further questions or concerns after reviewing the README, feel free to update this issue with more details."
