### ISSUE TITLE
Won't work from basic install

### ISSUE THREAD

**Issue by nigelp** [stackblitz-labs/bolt.diy#851]
### Describe the bug

Can't access models drop down once launched. Ever since bolt.new took .diy back, it's not worked properly or installed properly on Windows. 

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

1. installed bolt.diy from github (git clone)
2. installed dependencies
3. pnpm run dev
4. go to browser, main page loads, but nothing works. Only the model company lists, no models in right hand drop down.
5. can't access sidebar either. 

### Expected behavior

for the thing to work like it used to. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
windows 10
canary latest

**Comment by chrismahoney** [comment]
Fixed in #853, you should be access the model list now.
