### ISSUE TITLE
The left hidden menu bar does not expand

### ISSUE THREAD

**Issue by pesuga** [stackblitz-labs/bolt.diy#852]
### Describe the bug

On a completely fresh, error free install. I fired up with npm run dev and I quickly see the bolt interface.
The problem is that by click on the left bar icon does not expand the bar so I can't go into settings in order to input my API keys.
I even tried setting them up on the .env file but it didn't work.
Has this come up before?

### Link to the Bolt URL that caused the error

localhost

### Steps to reproduce

1. npm run dev
2. Click en menu icon

### Expected behavior

The menu shows up so one can go into settings

### Platform

- OS: MacOS
- Browser: Arc, also tried Chrome and Firefox
- Version: Latest

**Comment by barasnevicius** [comment]
Same problem, left menu does not appear when mouse pass or click on it:
![bolt](https://github.com/user-attachments/assets/c2a4a1df-6da4-4639-947c-13c81a9cce74)

**Comment by levert90** [comment]
For me too, there seems to be a compatibility issue with the new updates. it doesn't even let me choose the LLM models

**Comment by chrismahoney** [comment]
Fixed in #853 a short while ago, please update.

**Comment by cumhur** [comment]
Same problem on win11. Nothing work.

**Comment by chrismahoney** [comment]
Update to this commit, the specific issue is resolved.
