### ISSUE TITLE
I need a little help as I may have an issue with my setup.

### ISSUE THREAD

**Issue by hjyuh** [stackblitz-labs/bolt.diy#875]
### Describe the bug

Once I run ollama, the site pops up. When I try and prompt one of the models, I simply keep loading and loading, or states 'There was an error processing your request: Invalid or missing API key.' When I try to prompt Ollama, I get this.
![image](https://github.com/user-attachments/assets/be816d60-2650-4e1c-ac90-a731877661fd)
Just no option to select.

### Link to the Bolt URL that caused the error

I ran on local host.

### Steps to reproduce

I simply downloaded this following this doc: https://docs.google.com/document/d/19UNRP1c6ulDS_X7Ig7mRTI_EaT0xcvgimnfOJDKm7ig/edit?tab=t.0

### Expected behavior

I expected the qwen AI prompt option. 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/be816d60-2650-4e1c-ac90-a731877661fd)

### Platform

- OS: [ Windows,]
- Browser: [Firefox]
- Version: [e.g. 91.1]

### Model Used

All models dont work.

**Comment by Soumyaranjan-17** [comment]
show the screenshot of 
.env
your browser dev terminal 
and your Code editor terminal

**Comment by hjyuh** [comment]
hello,
 I managed to find and remove the error. 
 Thanks.

**Comment by Soumyaranjan-17** [comment]
Can you explain your problem and the steps to fix it
