### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by contabilulistet2** [stackblitz-labs/bolt.diy#905]
### Describe the bug

I m uploading images and none of them are shown.
![image](https://github.com/user-attachments/assets/129e6c5d-08a2-4427-ab41-6f02a61b3358)
the image is public on  Firebase 
- I can see the profile information of the user
- I can see the user Avatar on Netlify deployment
- I can't see the App logo, not even on Netlify where  I see the Avatars
-
### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

home page
upload image
image not show

### Expected behavior

image should render

### Platform

Win 11
Chrome
 Current Version Tag: v"0.0.3"
📍 Current Commit Version: "f9648d2"

### Provider Used

Gemini 2.0

**Comment by aproli90** [comment]
@contabilulistet2 Are you not facing this issue anymore?
