### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toolCalls') in stream-text.ts when using qwen2.5-coder:7b model

### ISSUE THREAD

**Issue by jyotiska222** [stackblitz-labs/bolt.diy#929]
### Describe the bug

When invoking the **qwen2.5-coder:7b** model using **_ollama_**, the process fails with the error:
```
TypeError: Cannot read properties of undefined (reading 'toolCalls')
    at Object.flush (app\lib\.server\llm\stream-text.ts)
```
This error occurs during the text streaming process, where the toolCalls property is accessed but is undefined.

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/2

### Steps to reproduce

1. Install ollama and ensure you have the qwen2.5-coder:7b model.
2. Run the following command to invoke the model: `ollama create -f Qwen2.5coder qwen2.5-coder:7b`
4. Observe the error when attempting to stream text using the model.

### Expected behavior

The streaming function should handle undefined toolCalls and proceed without throwing a TypeError. The error indicates a potential uninitialized or missing property.

### Screen Recording / Screenshot

A TypeError is thrown because the toolCalls property is undefined.
![Screenshot 2024-12-29 022533](https://github.com/user-attachments/assets/17b1a2c0-82fb-4f07-b5a7-d7faf4ceb745)
![Screenshot 2024-12-29 022631](https://github.com/user-attachments/assets/2e7d25eb-c92d-4d5f-8654-69c62987c372)

### Platform

OS: Windows 11 24H2
Ollama Version: [Insert Version]
Model Used: qwen2.5-coder:7b

**Comment by gabotrixinc** [comment]
Were you able to solve the problem?

**Comment by jyotiska222** [comment]
No.. Please help me out

**Comment by jyotiska222** [comment]
> Were you able to solve the problem?

No, Please Help me out

**Comment by gabotrixinc** [comment]
> > Were you able to solve the problem?
> 
> No, Please Help me out

The 1.5b model worked for me, but out of 100% of requests it creates code, and 90% of the time it seems like a GPT chat giving you instructions.

**Comment by jyotiska222** [comment]
> > > Were you able to solve the problem?
> > 
> > 
> > No, Please Help me out
> 
> The 1.5b model worked for me, but out of 100% of requests it creates code, and 90% of the time it seems like a GPT chat giving you instructions.

Did you try LM Studio ??

**Comment by jyotiska222** [comment]
> > > Were you able to solve the problem?
> > 
> > 
> > No, Please Help me out
> 
> The 1.5b model worked for me, but out of 100% of requests it creates code, and 90% of the time it seems like a GPT chat giving you instructions.

Not getting Any Responses
![Uploading Screenshot 2024-12-29 110258.png…]()

**Comment by AnderRedna** [comment]
Same problem here.
im trying using ai azure + litellm

**Comment by miningnome** [comment]
Same error here.
![image](https://github.com/user-attachments/assets/0827b2cc-a904-4ad9-bec3-28dac6fe19ea)

I fixed the issue moving from Direct Installation to Using Docker. Working directly with docker deployment worked fine for me.

**Comment by miningnome** [comment]
@jyotiska222 hmm! I've just seen a detail in the Direct Installation deployment. The "self.crossOriginIsolated" would be producing some issues in your end. Update your "vite.config.ts" to this setup:

`import { cloudflareDevProxyVitePlugin as remixCloudflareDevProxy, vitePlugin as remixVitePlugin } from '@remix-run/dev';
import UnoCSS from 'unocss/vite';
import { defineConfig, type ViteDevServer } from 'vite';
import { nodePolyfills } from 'vite-plugin-node-polyfills';
import { optimizeCssModules } from 'vite-plugin-optimize-css-modules';
import tsconfigPaths from 'vite-tsconfig-paths';

import { execSync } from 'child_process';

// Get git hash with fallback
const getGitHash = () => {
  try {
    return execSync('git rev-parse --short HEAD').toString().trim();
  } catch {
    return 'no-git-info';
  }
};

export default defineConfig((config) => {
  return {
    define: {
      __COMMIT_HASH: JSON.stringify(getGitHash()),
      __APP_VERSION: JSON.stringify(process.env.npm_package_version),
    },
    build: {
      target: 'esnext',
    },
    plugins: [
      nodePolyfills({
        include: ['path', 'buffer'],
      }),
      config.mode !== 'test' && remixCloudflareDevProxy(),
      remixVitePlugin({
        future: {
          v3_fetcherPersist: true,
          v3_relativeSplatPath: true,
          v3_throwAbortReason: true,
          v3_lazyRouteDiscovery: true,
        },
      }),
      UnoCSS(),
      tsconfigPaths(),
      chrome129IssuePlugin(),
      config.mode === 'production' && optimizeCssModules({ apply: 'build' }),
    ],
    envPrefix: [
      "VITE_",
      "OPENAI_LIKE_API_BASE_URL",
      "OLLAMA_API_BASE_URL",
      "LMSTUDIO_API_BASE_URL",
      "TOGETHER_API_BASE_URL",
    ],
    css: {
      preprocessorOptions: {
        scss: {
          api: 'modern-compiler',
        },
      },
    },
    server: {
      headers: {
        'Cross-Origin-Opener-Policy': 'same-origin',
        'Cross-Origin-Embedder-Policy': 'require-corp',
      },
    },
  };
});

function chrome129IssuePlugin() {
  return {
    name: 'chrome129IssuePlugin',
    configureServer(server: ViteDevServer) {
      server.middlewares.use((req, res, next) => {
        const raw = req.headers['user-agent']?.match(/Chrom(e|ium)\/([0-9]+)\./);

        if (raw) {
          const version = parseInt(raw[2], 10);

          if (version === 129) {
            res.setHeader('content-type', 'text/html');
            res.end(
              '<body><h1>Please use Chrome Canary for testing.</h1><p>Chrome 129 has an issue with JavaScript modules & Vite local development, see <a href="https://github.com/stackblitz/bolt.new/issues/86#issuecomment-2395519258">for more information.</a></p><p><b>Note:</b> This only impacts <u>local development</u>. `pnpm run build` and `pnpm run start` will work fine in this browser.</p></body>',
            );

            return;
          }
        }

        next();
      });
    },
  };
}
`

It worked for me also, so no more Docker is needed from my side :)

If it's not working for you, try to add a new file with name: "worker.js" with this content:
`
#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"
send_metrics = false

[build]
command = "pnpm run build"

[vars]
# Variable para configurar el host de Ollama
OLLAMA_HOST = "WRITE HERE YOUR OLLAMA URL AND PORT"

[[workers]]
# Configuración del worker para interceptar las respuestas y agregar encabezados
name = "bolt"
entry = "./worker.js" # Archivo que interceptará las respuestas

[pages]
# Configuración del directorio de salida
root = "./build/client"

[dev]
# Configuración de desarrollo
ip = "0.0.0.0"
port = 8788
compatibility_flags = ["nodejs_compat"]
`

Also you will need to modify your "wrangler.toml" with this data:

`#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"
send_metrics = false

[vars]
OLLAMA_HOST = "YOUR OLLAMA HOST AND PORT"

[pages]
root = "./build/client"
entrypoint = "./build/client"
functions = "./functions"

[functions]
# Agregar middleware para interceptar solicitudes y respuestas
main = "./functions/_middleware.js"
`

And finally (LOL) create a new functions/_middleware.js file:

`
export async function onRequest(context) {
  const response = await context.next();

  // Agregar encabezados necesarios para COOP y COEP
  response.headers.set("Cross-Origin-Opener-Policy", "same-origin");
  response.headers.set("Cross-Origin-Embedder-Policy", "require-corp");

  return response;
}
`

Maybe you will need to increase your max user watches to something like 500K:

`sudo sysctl fs.inotify.max_user_watches=524288
`

Also add to "/etc/sysctl.conf"

`fs.inotify.max_user_watches=524288
`

Update:
`sudo sysctl -p
`

And then try:
`pnpm run build
`

It worked for me, I hope you are luck also 👍 

![image](https://github.com/user-attachments/assets/63423f49-45b4-41fe-8276-c6b69068a732)

**Comment by jyotiska222** [comment]
Thanks for it..  I am currently running with LM studio and it's just working great after giving the  local server host in the `.env.local ` file  in the place of API key of LM studio 
But in the main project it's not updating the model in real time but it's working fine
